import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import Nav from "@/components/website/Nav";
import Footer from "@/components/website/Footer";

const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hostGrotesk.variable} antialiased w-full max-w-[1440px] min-h-screen mx-auto`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
